defaults: &defaults
    docker:
        - image: circleci/node:10.13
    working_directory: ~/repo

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Run Tests
                  command: npm run test
            # - run: |
            #       if [ $CIRCLE_BRANCH = "master" ]
            #       then
            #           npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            #           npm run release
            #       fi
    # deploy:
    #     <<: *defaults
    #     steps:
    #         - checkout
    #         - restore_cache:
    #               keys:
    #                   - v1-dependencies-{{ checksum "package.json" }}
    #                   - v1-dependencies-
    #         - run:
    #               name: Install Dependencies
    #               command: npm install
    #         - save_cache:
    #               paths:
    #                   - node_modules
    #               key: v1-dependencies-{{ checksum "package.json" }}
    #         - run:
    #               name: Publish to NPM
    #               command: |
    #                   npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    #                   npm publish

workflows:
    version: 2

    cd-pipeline:
        jobs:
            - build
            # - hold-for-approval:
            #       type: approval
            #       requires:
            #           - build
            # - deploy:
            #       requires:
            #           - hold-for-approval
