version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:10.13

jobs:
    build-and-test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Run Tests
                  command: npm run test
            - persist_to_workspace:
                  root: ~/repo
                  paths: .
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/repo
            - run:
                  name: Authenticate With Registry
                  command: npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            - run:
                  name: Config Git User
                  command: |
                      git config --global user.email "$EMAIL"
                      git config --global user.name "rosborne132"
            - run:
                  name: Bump Up Version Number
                  command: |
                      git add . && git commit -m "Bump up version number"
                      npm version premajor
            - run:
                  name: Publish Package
                  command: npm run package:publish

workflows:
    version: 2

    cd-pipeline:
        jobs:
            - build-and-test
            - hold-for-approval:
                  type: approval
                  requires:
                      - build-and-test
            - deploy:
                  requires:
                      - hold-for-approval
