defaults: &defaults
    docker:
        - image: circleci/node:10.13
    working_directory: ~/repo

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run test
            - run:
                  name: Publish Storybook Dev
                  command: |
                      npm run build-storybook
                      now -t ${NOW_TOKEN} --prod
            # - run:
            #       name: Publish to NPM
            #       command: |
            #           npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            #           npm publish
            # - run: npm run storybook:publish
    deploy:
        <<: *defaults
        type: approval
        requires:
            - build
        steps:
            - run:
                  name: Publish to NPM
                  command: |
                      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                      npm publish
